package lk.ijse.pharmacy.util;

public enum Routes {
    CUSTOMER, PLACE_ORDER, ADDCUSTOMER , ADD_EMPLOYEE , SUPPLIER , SPONSOR , MEDICINE , ITEM , DASHBOARD , LOGIN , BACK ,ADMIN , CASHIER ,PASSWORD
}
